services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      - PYTHONPATH=.
    ports:
      - "8000:8000"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
