[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]  # ordenar imports
ignore = ["E501"]      # no fallar por longitud de línea

[tool.ruff.format]
quote-style = "double"
