name: CI

on:
  push:
    branches: [ main, develop, "feat/**", "fix/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Unit tests (pytest)
        env:
          PYTHONPATH: .
        run: |
          pytest -q

      - name: API smoke test (fastapi)
        if: always()
        env:
          PYTHONPATH: .
        run: |
          python - << 'PY'
          import json
          from fastapi.testclient import TestClient
          from src.api.main import app
          c = TestClient(app)
          r = c.get("/health"); assert r.status_code == 200
          m = c.get("/model_meta"); assert m.status_code == 200
          print("SMOKE OK")
          PY
