      - name: API smoke test (fastapi)
        env:
          PYTHONPATH: .
        run: |
          python - << 'PY'
          from fastapi.testclient import TestClient
          from src.api import deps
          from src.api.main import app

          # --- Mock: evitar carga de modelos reales en CI ---
          class _DummyPipe:
              def predict_proba(self, X):
                  import numpy as np
                  return np.c_[1-np.full(len(X), 0.7), np.full(len(X), 0.7)]

          def _fake_get():
              return _DummyPipe(), {"columns": ["a","b"], "best_threshold_f1": 0.6}

          deps.get_model_and_meta.cache_clear()
          deps.get_model_and_meta = _fake_get  # monkeypatch simple

          c = TestClient(app)
          assert c.get("/health").status_code == 200
          assert c.get("/model_meta").status_code == 200
          print("SMOKE OK")
          PY
