      - name: API smoke test (fastapi, mocked model)
        if: always()
        env:
          PYTHONPATH: .
        run: |
          python - << 'PY'
          # --- Mock del modelo para evitar depender de artefactos reales en CI ---
          from fastapi.testclient import TestClient
          from src.api import deps
          from src.api.main import app

          class _DummyPipe:
              def predict_proba(self, X):
                  import numpy as np
                  return np.c_[1-np.full(len(X), 0.7), np.full(len(X), 0.7)]

          def _fake_get():
              return _DummyPipe(), {"columns": ["a","b"], "best_threshold_f1": 0.6}

          try:
              deps.get_model_and_meta.cache_clear()
          except Exception:
              pass
          deps.get_model_and_meta = _fake_get  # monkeypatch simple

          c = TestClient(app)
          assert c.get("/health").status_code == 200
          r = c.get("/model_meta")
          assert r.status_code == 200
          assert "best_threshold_f1" in r.json()
          print("SMOKE OK")
          PY

